name: end

on:
  workflow_run:
    workflows:
      - start
    types:
      - completed

permissions: { }

jobs:
  end1:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20


    steps:
      - name: end
        run: echo "------end------"
