name: Android CI - on pull_request

on:
  push:
    branches:
      - main

permissions: {}


jobs:
  start1:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20


    steps:
      - name: Start
        run: |
          echo "------Start1 starts------"
          sleep 5
          echo "------Start1 ends------"

  start2:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [start1]
    steps:
      - name: Start2
        run: |
          echo "------Start2 starts------"
          sleep 5
          echo "------Start2 ends------"
